Ansible 2
Otus-DevOps-2022-02/DmitryTeplov182_infra pull request #8
Opened 2022-05-17 12:00 UTC by DmitryTeplov182

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Собрал плейбуки
 - Пересобрал образы
 - Подключил инвентори

## Как запустить проект:
 - Развернуть stage окружение tf
 - прокатить плейбук site

## Как проверить работоспособность:
 - Перейти по ссылке http://reddit-app:9292

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-05-18 08:51 UTC, mrgreyves requested changes
Здравствуйте!)
Нужно пофиксить ansible.cfg, там в нем есть ошибочка =)

2022-05-18 08:51 UTC, mrgreyves commented on ansible/ansible.cfg
> +Убрал, потому что тесты не проходят
Вот эту строку лучше добавить в комент =)
Из-за нее как раз тесты и не проходят =)

2022-05-22 10:20 UTC, DmitryTeplov182 commented on ansible/ansible.cfg
> +Убрал, потому что тесты не проходят
Тесты точно по другой причине не проходили, я там тупил в одном месте. Поправил коммент, спасибо

2022-05-22 10:42 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув =)

2022-05-22 11:00 UTC, merged